---
leaf1-ios:
    hostname: 172.29.151.3
    groups:
        - ios

leaf2-ios:
    hostname: 172.29.151.4
    groups:
        - ios

leaf3-qfx:
    hostname: 172.29.151.5
    groups:
        - junos

leaf4-qfx:
    hostname: 172.29.151.6
    groups:
        - junos

leaf5-eos:
    hostname: 172.29.151.7
    groups:
        - eos

leaf6-eos:
    hostname: 172.29.151.8
    groups:
        - eos

#<fqdn>:
#    hostname: <fqdn> or <ip address>
#    groups:
#        - nxos


